#
# this playbook takes the files from the repo and puts them into the correct place in the servers 
#
#
#
---
- hosts: localhost
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: install files from repo into runtime location
    copy: 
      src:  "{{ REPO }}/{{ item.src }}"
      dest: "{{ RUN }}/{{ item.dest }}"
      owner : "{{ item.o }}" 
      group : "{{ item.g }}"
      mode : "{{ item.mode }}"
    with_items:
      - { src: 'heading_calc.py',  dest: 'heading_calc.py',  mode: '0655', o: 'pi',   g: 'pi' }
      - { src: 'SevenSeg.py',      dest: 'SevenSeg.py',      mode: '0655', o: 'pi',   g: 'pi' }
      - { src: 'kplex-monitor.py', dest: 'kplex-monitor.py', mode: '0655', o: 'pi',   g: 'pi' }
      - { src: 'boot_test.sh',     dest: 'boot_test.sh',     mode: '0655', o: 'pi',   g: 'pi' } 
      - { src: 'boot_test.txt',    dest: 'boot_test.txt',    mode: '0644', o: 'pi',   g: 'pi' } 
      - { src: 'Run_test.sh',      dest: 'Run_test.sh',      mode: '0655', o: 'pi',   g: 'pi' } 
      - { src: 'environs.sh',      dest: 'environs.sh',      mode: '0655', o: 'pi',   g: 'pi' } 
      - { src: 'shutdown.py,       dest: 'shutdown.py',      mode: '0655', o: 'root', g: 'root' } 
      - { src: 'kplex_server_simulator.sh', dest: 'kplex_server_simulator.sh', mode: '0655', o: 'pi', g: 'pi'} 
  
  - name Instal kplex server 
    paclage: 
       name: kplex 
       state: present 

  - name: Install boot diag script in cron 
    cron: 
      name: "Feed example compass data to kplex server on boot for diagnostics"
      special_time: reboot 
      cron_file: diag_boot
      user: root 
      job:  "{{ RUN }}/boot_test.sh" 

  - name: Install kplex system config files
    copy:
      src: "{{ REPO }}/etc_kplex.conf"
      dest: /etc/kplex.conf 
      mode: '0644'
      owner: root
      group: root
  
  - name: install service daemons 
    copy:
      src:  "{{ REPO }}/{{ item.file }}"
      dest: "/etc/systemd/system/{{ item.file }}"
      owner : root 
      group : root
      mode : "{{ item.mode }}"
    with_items:
      - { file: 'kplex-monitor.service',  mode: '0655' }
      - { file: 'shutdown.service',  mode: '0655' }

  - name: Enable shutdown button monitoring and start services, dont start it yet  
    service: 
      name:  shutdown
      daemon_reload: yes 
      enabled: yes
      state: stopped 
    service: 
      name: kplex-monitor 
      daemon_reload: yes 
      enabled:  yes
      state: stopped 

  - name: Start up kplex if neeed 
    service: 
      name: kplex 
      enabled: yes 
      state: started
 
