#
# this playbook takes the files from the repo and puts them into the correct place in the servers 
#
#
#
---
- hosts: localhost
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: install files from repo into runtime location
    copy: 
      src:  "{{ REPO }}/{{ item.src }}"
      dest: "{{ RUN }}/{{ item.dest }}"
      owner : pi 
      group : pi
      mode : "{{ item.mode }}"
    with_items:
      - { src: 'heading_calc.py',  dest: 'heading_calc.py',  mode: '0655' }
      - { src: 'SevenSeg.py',      dest: 'SevenSeg.py',      mode: '0655' }
      - { src: 'kplex_monitor.py', dest: 'kplex_monitor.py', mode: '0655' }
      - { src: 'boot_test.sh',     dest: 'boot_test.sh',     mode: '0655' } 
      - { src: 'boot_test.txt',    dest: 'boot_test.txt',    mode: '0644' } 
      - { src: 'Run_test.sh',      dest: 'Run_test.sh',      mode: '0655' } 
      - { src: 'environs.sh',      dest: 'environs.sh',      mode: '0655' } 
      - { src: 'kplex_server_simulator.sh', dest: 'kplex_server_simulator.sh',   mode: '0655'} 
  
  - name: Install boot diag script in cron 
    cron: 
      name: "Feed example compass data to kplex server on boot for diagnostics"
      special_time: reboot 
      cron_file: diag_boot
      user: root 
      job:  "{{ RUN }}/boot_test.sh" 


